### ISSUE TITLE
Support for DNS load balancers

### ISSUE THREAD

**Issue by 0x566164696D** [wallarm/api-firewall#102]
There are several methods of load balancing traffic using DNS:

- Round robin DNS
- Returning the IP address of a live host in response to a DNS query
- etc.

Currently, API-Firewall cannot work with such load balancers and performs DNS resolution only at startup.
During operation, DNS may point to a different A record, but API-Firewall will continue trying to send requests to the old IP address.

Please add support for DNS load balancers so that DNS resolution occurs periodically and connects to the new IP (transparently to the end user, without service degradation).

**Comment by afr1ka** [comment]
We have added support for DNS cache and DNS async cache update. Please check the doc [here](https://wallarm.github.io/api-firewall/configuration-guides/dns-cache-update/)
