### ISSUE TITLE
Question about settings

### ISSUE THREAD

**Issue by shrv** [wallarm/api-firewall#12]
Hello, team Wallarm.
I have studied your documentation, i have a question.
Tell me if it is possible to change the http response code in the blocking mode through variables. By default, as I understand it, it is 403.
But sometimes it is more convenient to be able to set your own response code, for accurate diagnostics by logs, or for introducing a custom page when blocking the api by a firewall.

**Comment by d0znpp** [comment]
Hi there! Thanks for your support of our project. We will add to the custom status code configuration as you requested. A custom page seems less reasonable since API responses should be on the backend side.

Could you please explain your use case in a bit more detail?

**Comment by shrv** [comment]
Hi, Ivan.
I agree that this is how it should be. 
But not when the application is on the user's side and for part of the api requests  generates some action, when receiving 403. It doesn't always seem right to generate 403 from the firewall API. It seems better to generate a different response code. Additionally, this may make it easier to filter requests that were blocked by the Firewall in the general Nginx log.

**Comment by d0znpp** [comment]
we will implement custom codes soon

**Comment by d0znpp** [comment]
Please check if the ```APIFW_CUSTOM_BLOCK_STATUS_CODE``` parameter works for you.

**Comment by shrv** [comment]
I'll check it out and come back with an answer

**Comment by MrEcco** [comment]
Hi @shrv!

You are welcome to try the feature with the new version. We will update the documentation about this soon. And thank you for your support!

For now, you can look at the flags/envs by the command:
```
docker run --rm -it wallarm/api-firewall:v0.6.4 -h

# You are see here the entry:
#   --custom-block-status-code/$APIFW_CUSTOM_BLOCK_STATUS_CODE          <int>           (default: 403)
```
