### ISSUE TITLE
Bypass Upstream Certificate Checking

### ISSUE THREAD

**Issue by swarmee** [wallarm/api-firewall#24]
Is there a configuration parameter to bypass the certificate validity checking for upstream / proxied APIs?

This is the error I am getting
{"level":"error","msg":"#0000000100000001 : error while proxying request: x509: certificate is valid for abc.xyz.net not abc","time":"2021-11-17T10:44:07Z"}

This would be helpful for self signed certificates and networks that are not directly internet accessible.

**Comment by afr1ka** [comment]
Hello swarmee,

Unfortunately, there is no such option right now. We will add this functionality to the next release - v0.6.6.

Thanks.

**Comment by swarmee** [comment]
Wow thanks for your quick response. I'll look forward to the next releases. 
Thanks again.

**Comment by swarmee** [comment]
Sorry if its documented somewhere and I missed it - can you let me know the parameter to pass to skip upstream TLS certificate validation (for when I am using self signed certificates internally).

**Comment by afr1ka** [comment]
There are several options here:

- Set APIFW_SERVER_INSECURE_CONNECTION parameter value to "true".
- Set the path to your root CA via the APIFW_SERVER_ROOT_CA parameter.

Full documentation is available [here](https://docs.wallarm.com/api-firewall/installation-guides/docker-container/#protected-application-ssltls-settings).
