### ISSUE TITLE
Pass API schema via URL

### ISSUE THREAD

**Issue by Olegt0rr** [wallarm/api-firewall#34]
In some cases API schema is available on URL.
Please add a feature with passing an URL instead of mounting a file.

**Comment by d0znpp** [comment]
Add support of the OpenAPI spec loading via URL. From now on it's possible to set openapi specification URL to env var APIFW_API_SPECS.
Add custom Content-Type of the request to introspection endpoint. Custom content-type could be set to the env var APIFW_SERVER_OAUTH_INTROSPECTION_CONTENT_TYPE.

You can view, comment on, or merge this pull request online at:
  https://github.com/wallarm/api-firewall/pull/40

**Comment by d0znpp** [comment]
https://github.com/wallarm/api-firewall/pull/40
