### ISSUE TITLE
Feature Suggestion - x509 key pair authentication

### ISSUE THREAD

**Issue by kbrewer92** [wallarm/api-firewall#38]
This application is a really nice tool and I can imagine numerous applications for this model. What I would like to suggest is an additional module that would allow for zero trust via x509 key pair. This would allow users to deploy unconfigured versions on their applications and the said application could just auth with a key pair, request what it needs to request for an initial configuration download. 

Private key verification could be integrated into cloud-based key storage like Google KMS, an intermediate CA, or even stored locally on the host machine's file system or k8s secrets.

**Comment by d0znpp** [comment]
Do you mean client SSL certificate?

**Comment by d0znpp** [comment]
already supported

**Comment by MrEcco** [comment]
> auth with a key pair

@kbrewer92 Did you mean [mutual TLS authentication](https://en.wikipedia.org/wiki/Mutual_authentication)?
