### ISSUE TITLE
Response validation failed with empty content type

### ISSUE THREAD

**Issue by mx237** [wallarm/api-firewall#56]
I set `APIFW_RESPONSE_VALIDATION=BLOCK` and got the following error:
`level=error msg=response validation error error=response header Content-Type has unexpected value: "" request_id=#0000000100000001`

I suspect it's due to this code in `cmd/api-firewall/internal/handlers/openapi.go`
```go
	// Prepare http response headers
	respHeader := http.Header{}
	ctx.Request.Header.VisitAll(func(k, v []byte) {
		sk := string(k)
		sv := string(v)

		respHeader.Set(sk, sv)
	})
```
It seems to obtain the http headers from request rather than response. Should `ctx.Request` be changed to `ctx.Response`?

**Comment by afr1ka** [comment]
Hello mx237,

Yes, you are right. Will be fixed in 0.6.11.

Thanks
