### ISSUE TITLE
Unable to parse response data with http compression

### ISSUE THREAD

**Issue by mx237** [wallarm/api-firewall#57]
The http request sent from api-firewall to the server contains this http header: `Accept-Encoding: gzip, deflate, br`, which means it accepts compressed data.
When the server response is compressed with http header, e.g. `content-encoding: gzip`, it's unable to parse the response without decompression.

**Comment by afr1ka** [comment]
Will be fixed in 0.6.11. Thanks.

**Comment by afr1ka** [comment]
Added decompression support of the following encoding schemas: gzip, br and deflate. 
Also, added APIFW_SERVER_DELETE_ACCEPT_ENCODING env var (possible values are True or False). If the value is True then the Accept-Encoding header will be deleted from proxied requests. The default value is False.
