### ISSUE TITLE
The lack of necessary information in the logs, JSON format.

### ISSUE THREAD

**Issue by 0x566164696D** [wallarm/api-firewall#78]
Information about the "path" is missing for the following events:

    "request body has an error: doesn't match schema"
    "value is required but missing"
    "Shadow API: undefined parameters found"

This makes it extremely inconvenient to monitor the API Firewall's request processing, especially when multiple containers are running and a log aggregator like Open Observe is being used.

Please add output information about the "path".

**Comment by afr1ka** [comment]
Will add additional info to these messages in the v0.6.16.
As a fast mitigation you can try to use DEBUG or TRACE log mode. In this mode you will find an extra messages with the full request/response data in the log.
