### ISSUE TITLE
The use of line breaks in log formatting in the TEXT format.

### ISSUE THREAD

**Issue by 0x566164696D** [wallarm/api-firewall#79]
The use of line breaks significantly complicates parsing with popular log collection tools (such as OpenObserve, Filebeat, Logstash, Fluentd, Vector, etc).

Some events, for example, "request validation error", are split into multiple lines, making it difficult to parse logs properly and work with them.

I request a change in formatting to avoid using \r\n as a separator within a single event.

**Comment by afr1ka** [comment]
Will fix it in the v0.6.16. Thanks for the suggestion.
