### ISSUE TITLE
Non-unique request_id.

### ISSUE THREAD

**Issue by 0x566164696D** [wallarm/api-firewall#80]
It has been noticed that the request_id is incremental, leading to issues when running multiple API-Firewall containers and using log collection systems (such as OpenObserve). Consequently, unrelated events may be assigned the same request_id.

I request to implement the generation of unique request_id values.

**Comment by afr1ka** [comment]
Hello 0x566164696D,
Will fix it in the v0.6.16. Thanks for the suggestion.
