### ISSUE TITLE
More flexible Proxy configuration in API-Firewall

### ISSUE THREAD

**Issue by 0x566164696D** [wallarm/api-firewall#97]
Currently, proxying is configured only through --server-url.
If --server-url contains a DNS name, it is resolved to an IP, a connection is established with this IP, and the DNS name is written to header_host.
If an IP address is specified, the connection is made to it, and it is also placed in the header_host of the HTTP request.

This approach is not flexible enough.
Please add an additional launch key where an arbitrary header_host can be specified.
This will significantly simplify the integration of API-Firewall into the infrastructure.

**Comment by afr1ka** [comment]
Added the APIFW_SERVER_REQUEST_HOST_HEADER env variable to set the custom host value for proxied requests in APIFW v0.7.3.
